---
- name: Install Apache and Upload my Web
  become: yes

  vars:
    sourse_file: ./MyWebSite/index.html 
    destin_file: /var/www/html

  tasks:
  - name: Install Apache Web Server
    yum: name=httpd stato=latest

  - name: Copy MyHomePage to Servers
    copy: src={{ sourse_file }} dest={{ destin_file }} mode=0555
    notyfy: Restart Apache

  - name: Start WebServer and make it enable on boot
    service: name=httpd state=started enabled=yes

  hendlers:
  - name: Restart Apache
    service: name=httpd state=restarted
